"""initial schema

Revision ID: f08a4a90af44
Revises: 
Create Date: 2026-06-14 21:48:48.695188
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'f08a4a90af44'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_log',
    sa.Column('message_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=32), nullable=False),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('classification_snapshot', sa.JSON(), nullable=False),
    sa.Column('destination_id', sa.Uuid(), nullable=True),
    sa.Column('destination_record_id', sa.String(length=128), nullable=True),
    sa.Column('destination_record_url', sa.String(length=512), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_message_id'), 'audit_log', ['message_id'], unique=False)
    op.create_index(op.f('ix_audit_log_tenant_id'), 'audit_log', ['tenant_id'], unique=False)
    op.create_table('classifications',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('intent', sa.String(length=32), nullable=False),
    sa.Column('person_name', sa.String(length=255), nullable=True),
    sa.Column('person_appears_to_be', sa.String(length=64), nullable=True),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('company_domain_hint', sa.String(length=255), nullable=True),
    sa.Column('phone_e164', sa.String(length=20), nullable=True),
    sa.Column('language', sa.String(length=8), nullable=False),
    sa.Column('summary_one_line', sa.Text(), nullable=False),
    sa.Column('suggested_record_type', sa.String(length=32), nullable=True),
    sa.Column('confidence_overall', sa.Float(), nullable=False),
    sa.Column('confidence_intent', sa.Float(), nullable=False),
    sa.Column('confidence_person', sa.Float(), nullable=False),
    sa.Column('confidence_company', sa.Float(), nullable=False),
    sa.Column('model_used', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_classifications_message_id'), 'classifications', ['message_id'], unique=False)
    op.create_index(op.f('ix_classifications_tenant_id'), 'classifications', ['tenant_id'], unique=False)
    op.create_table('crm_cache',
    sa.Column('external_record_id', sa.String(length=128), nullable=False),
    sa.Column('record_type', sa.String(length=32), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('company', sa.String(length=255), nullable=True),
    sa.Column('phones', sa.JSON(), nullable=False),
    sa.Column('emails', sa.JSON(), nullable=False),
    sa.Column('source_destination_id', sa.Uuid(), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_cache_tenant_id'), 'crm_cache', ['tenant_id'], unique=False)
    op.create_table('destinations',
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('field_mapping', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_destinations_tenant_id'), 'destinations', ['tenant_id'], unique=False)
    op.create_table('eval_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('golden_set_version', sa.String(length=32), nullable=False),
    sa.Column('model', sa.String(length=64), nullable=False),
    sa.Column('prompt_version', sa.String(length=32), nullable=False),
    sa.Column('overall_accuracy', sa.Float(), nullable=False),
    sa.Column('per_field', sa.JSON(), nullable=False),
    sa.Column('calibration', sa.JSON(), nullable=False),
    sa.Column('per_language', sa.JSON(), nullable=False),
    sa.Column('confusion', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('identity_resolutions',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_ids', sa.JSON(), nullable=False),
    sa.Column('decision', sa.String(length=16), nullable=False),
    sa.Column('decided_by', sa.String(length=64), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('considered', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_identity_resolutions_message_id'), 'identity_resolutions', ['message_id'], unique=False)
    op.create_index(op.f('ix_identity_resolutions_tenant_id'), 'identity_resolutions', ['tenant_id'], unique=False)
    op.create_table('inbox_items',
    sa.Column('message_id', sa.Uuid(), nullable=False),
    sa.Column('classification_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('band', sa.String(length=8), nullable=False),
    sa.Column('assigned_action', sa.JSON(), nullable=True),
    sa.Column('resolved_by', sa.String(length=64), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_inbox_items_message_id'), 'inbox_items', ['message_id'], unique=False)
    op.create_index(op.f('ix_inbox_items_tenant_id'), 'inbox_items', ['tenant_id'], unique=False)
    op.create_table('messages',
    sa.Column('wa_message_id', sa.String(length=128), nullable=False),
    sa.Column('wa_chat_id', sa.String(length=64), nullable=False),
    sa.Column('sender_phone_e164', sa.String(length=20), nullable=False),
    sa.Column('sender_wa_name', sa.String(length=255), nullable=True),
    sa.Column('direction', sa.String(length=16), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('media_id', sa.String(length=128), nullable=True),
    sa.Column('media_mime', sa.String(length=128), nullable=True),
    sa.Column('transcript_text', sa.Text(), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'wa_message_id', name='uq_messages_tenant_wamid')
    )
    op.create_index(op.f('ix_messages_tenant_id'), 'messages', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_messages_wa_chat_id'), 'messages', ['wa_chat_id'], unique=False)
    op.create_table('rules',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('action', sa.JSON(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rules_tenant_id'), 'rules', ['tenant_id'], unique=False)
    op.create_table('sources',
    sa.Column('wa_chat_id', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=True),
    sa.Column('excluded', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'wa_chat_id', name='uq_sources_tenant_chat')
    )
    op.create_index(op.f('ix_sources_tenant_id'), 'sources', ['tenant_id'], unique=False)
    op.create_table('tenants',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('tier', sa.String(length=32), nullable=False),
    sa.Column('control_chat_phone_e164', sa.String(length=20), nullable=True),
    sa.Column('waba_id', sa.String(length=64), nullable=True),
    sa.Column('phone_number_id', sa.String(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tenants')
    op.drop_index(op.f('ix_sources_tenant_id'), table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_rules_tenant_id'), table_name='rules')
    op.drop_table('rules')
    op.drop_index(op.f('ix_messages_wa_chat_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_tenant_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_inbox_items_tenant_id'), table_name='inbox_items')
    op.drop_index(op.f('ix_inbox_items_message_id'), table_name='inbox_items')
    op.drop_table('inbox_items')
    op.drop_index(op.f('ix_identity_resolutions_tenant_id'), table_name='identity_resolutions')
    op.drop_index(op.f('ix_identity_resolutions_message_id'), table_name='identity_resolutions')
    op.drop_table('identity_resolutions')
    op.drop_table('eval_runs')
    op.drop_index(op.f('ix_destinations_tenant_id'), table_name='destinations')
    op.drop_table('destinations')
    op.drop_index(op.f('ix_crm_cache_tenant_id'), table_name='crm_cache')
    op.drop_table('crm_cache')
    op.drop_index(op.f('ix_classifications_tenant_id'), table_name='classifications')
    op.drop_index(op.f('ix_classifications_message_id'), table_name='classifications')
    op.drop_table('classifications')
    op.drop_index(op.f('ix_audit_log_tenant_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_message_id'), table_name='audit_log')
    op.drop_table('audit_log')
    # ### end Alembic commands ###
